#Location: ~/.config/starship.toml
#What_is_starship: https://starship.rs/

add_newline = true
command_timeout = 2000

format = """$env_var$username$hostname$directory$git_branch$git_status
$character
"""

[character]
success_symbol = "‚ï∞‚éØÔÑÖ"
error_symbol = "‚ï∞‚éØÔÑÖ"
# ‚ï≠‚ï¥ ‚ï∞‚îÄ

[env_var]
symbol = "‚ï≠‚ï¥"
variable = "SHELL"
format = "$symbol"
disabled = false


#warp-Drop ugly default prompt characters
#success_symbol = ""
#error_symbol = ""

# Shows the username
[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[//](black bold) [$user](#2883ff) " # 2883ff
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = "[//](black bold) [$hostname](bold blue) "
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = "‚Ä¶/"
home_symbol = "~"
# read_only_style = "197"
read_only = " ÔÄ£ "
format = "[//](black bold) [$path]($style)[$read_only]($read_only_style) "
#style = "#7ed1fb" # yellow bold
style = "yellow bold"


# Shows current git branch
[git_branch]
always_show_remote = true
symbol = "Ôêò"
format = "[//](black bold) [$symbol ($remote_name/)$branch]($style)"
style = "bold green"

# Shows current git status
[git_status]
#disabled = false
format = "[ $all_status$ahead_behind]($style)"
style = "bold green"
conflicted = "üè≥"
up_to_date = ""
untracked = "Ôî© "
ahead = "‚á°${count}"
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"
stashed = "Ô£ñ "
modified = "ÔÅÑ "
staged = "[++($count)](green)"
renamed = "Ë•Å "
deleted = "ÔÄî "



# Shows kubernetes context and namespace
[kubernetes]
format = "via [Û±Éæ $context($namespace)](bold purple) "
disabled = true

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true
symbol = "Û∞å†"
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
format = "[//](black bold) [${symbol} ${pyenv_prefix}(${version} )(($virtualenv) )]($style) "


[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
